version: "3.1"

services:
  bugzilla:
    image: herzcthu/bugzilla:latest
    build:
      context: .
    container_name: bugzilla
    volumes:
      - ./localconfig:/usr/local/apache2/htdocs/localconfig
    ports:
      - "80:80"
      - "5900:5900"
    links:
      - mysql
    restart: always
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugs
      - MYSQL_USER=bugs
      - MYSQL_PASSWORD=bugs
    restart: always
    networks:
      - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER:-bridge}
    ipam:
      driver: default
      config:
      - subnet:  ${FRONTEND_SUBNET:-192.168.168.0/25}

  backend:
    driver: ${NETWORKS_DRIVER:-bridge}
    ipam:
      driver: default
      config:
      - subnet: ${BACKEND_SUBNET:-192.168.168.128/25}
