version: "3.1"

services:
  bugzilla:
    image: herzcthu/bugzilla:latest
    build:
      context: .
    container_name: bugzilla
    volumes:
      - ./localconfig:/usr/local/apache2/htdocs/localconfig
    ports:
      - "80:80"
      - "5900:5900"
    restart: always



